// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServicioRestCore;

#nullable disable

namespace ServicioRestCore.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240628211923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServicioRestCore.Models.Categoria", b =>
                {
                    b.Property<int>("codcat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codcat"));

                    b.Property<bool>("escat")
                        .HasColumnType("bit");

                    b.Property<string>("nomcat")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("codcat");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ServicioRestCore.Models.Producto", b =>
                {
                    b.Property<int>("codpro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codpro"));

                    b.Property<double>("canpro")
                        .HasColumnType("float");

                    b.Property<int>("codcat")
                        .HasColumnType("int");

                    b.Property<string>("despro")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("estpro")
                        .HasColumnType("bit");

                    b.Property<string>("nompro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("prepro")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("codpro");

                    b.HasIndex("codcat");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ServicioRestCore.Models.Producto", b =>
                {
                    b.HasOne("ServicioRestCore.Models.Categoria", "categoria")
                        .WithMany("producto")
                        .HasForeignKey("codcat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("ServicioRestCore.Models.Categoria", b =>
                {
                    b.Navigation("producto");
                });
#pragma warning restore 612, 618
        }
    }
}
